title: Uche's Blog
author: uonyekwuluje
email: uionyekwuluje@gmail.com
description: > 
  Software Development, DevOps, Site Reliability Engineering, AWS, GCP, Azure
  Linux, Sysops
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Uchechukwu Onyekwuluje
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    github:  uonyekwuluje
    linkedIn: in/uchechukwu-onyekwuluje-sde
    rss: rss
     linkedin: jekyll

header_pages:
 - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
