title: Uche's Tech Corner | The little things matter
email: uionyekwuluje@gmail.com
url: https://uonyekwuluje.github.io/
description: DevOps, Site Reliability, Clouds
#baseurl: "" # the subpath of your site, e.g. /blog
baseurl: ""
url: ""
github_username: uonyekwuluje

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
