title: "Coding, Toolsmith, Systems"
author: "Uchechukwu Onyekwuluje"
description: "DevOps, Site Reliability, AWS, GCP, Azure"

permalink: /:year-:month-:day/:title/
paginate: 666666n"

show_footer: true           # show the "previous" and "next" links at the end of each post | false
dark_theme: false            # use the dark mode as default  | false
dark_header: true            # keep the header dark          | true
dark_footer: true           # keep the footer dark           | false

navigation:                  # site navigation in the header
  - README.md
  - Github: "http://github.com/uonyekwuluje"
  - CONTACTME.md

#  icons:    http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github:   "https://github.com/niklasbuschmann/contrast"
#  rss:      "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
 - jekyll-paginate
