title: Let's talk DevOps, Site Reliability, Clouds
email: ""
url: https://uonyekwuluje.github.io/
description: DevOps, Site Reliability, Clouds
baseurl: ""
url: ""
github_username: uonyekwuluje

# Build settings
markdown: kramdown

paginate: 10

theme: minima
